[tool.poetry]
name = "assn-python-autograding-2-may-3-kkarim"
version = "0.1.0"
description = ""
authors = ["mrkarim <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
